### PR TITLE
Use code when rejecting connection

### LINKED ISSUE #486: Implement WebSocket Denial Response extension
The value for `code` is hard coded to `403` when close happens while connecting

### PR DESCRIPTION
**Pull request by daveisfera**
Fixed #486

### CODE REVIEW

**Comment by carltongibson** [comment]
Can we add a regression test for this change?

**Comment by daveisfera** [comment]
I'm not familiar with the tests. Can you point me to where that would be added?

**Comment by Kludex** [comment]
This PR is wrong. Daphne doesn't support WebSocket Denial Response. The status code 403 is correct.

The `message["code"]` is not a HTTP status code.

**Comment by daveisfera** [comment]
> This PR is wrong. Daphne doesn't support WebSocket Denial Response. The status code 403 is correct.
> 
> The `message["code"]` is not a HTTP status code.

I'm not sure what that's supposed to mean. I've tested this change and it works

**Comment by carltongibson** [comment]
Closing as per ticket.

**Pull request closed without merging**
