### PR TITLE
issues #116 - log rotation with logrotate.d

### PR DESCRIPTION
**Pull request by waikup83**
For implentation exemple

File in /etc/logrotate.d/daphne

/directory/of/log/daphne.log {
    su root root
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    create 0640 www-data adm
    sharedscripts
    postrotate
	ps aux | grep -v grep | grep '/directory/running/daphne' | awk '{system("kill -USR1 "$2)}'
    endscript
}

test : logrotate -f daphne

### CODE REVIEW

**Comment by waikup83** [comment]
Its hard to test the behaviour of logrotate.d ... no?

**Comment by carltongibson** [comment]
Surely we can send the signal and check that the the handler works correctly (i.e that the log files are correctly swapped)?

**Comment by waikup83** [comment]
maybe … but now i have not sush time to check how test are allready integrated and do one :/

**Comment by waikup83** [comment]
So you want a test.py to test if newly file is created ?!

**Comment by carltongibson** [comment]
Hi @waikup83. I'm working on a set of releases here for September, so I'll give this a run before then, and add a test for the signal handler. Thank you for the input!!!

**Comment by carltongibson** [comment]
Discussion in #116 leans to **not** adding this directly in Daphne (but moving to use Python's logging framework as an orthogonal improvement). Thanks

**Pull request closed without merging**
