### PR TITLE
removed deferToThread for ASGI instance constructor

### PR DESCRIPTION
**Pull request by JohnDoee**
As it is not needed anymore (per #188 comment) it should be removed to remove confusion and because it should be unnecessary.

### CODE REVIEW

**Comment by tomchristie** [comment]
Refs: https://github.com/encode/uvicorn/issues/129

**Comment by andrewgodwin** [comment]
Can you rebase to see if you can get Travis to run the tests correctly?

**Comment by JohnDoee** [comment]
The error message opaqueness was a case of Twisted being Twisted. Bug fixed and tests look fine now.

**Comment by andrewgodwin** [comment]
Great, thanks!

**Pull request merged**
