### PR TITLE
Fix autobahn minimum required version from 0.12 to 0.18

### PR DESCRIPTION
**Pull request by pamungkaski**
#101  
### Proposed changes in this pull request

- change the autobahn minimum required version on setup.py

### When should this PR be merged

- Anytime

### Risks

- Null

### Follow-up actions

- Null

### CODE REVIEW

**Comment by pamungkaski** [comment]
dont know why fail, nothing changed except the minimum reqiured version of autobahn

**Comment by andrewgodwin** [comment]
The master branch of daphne is currently failing due to a missing `asgiref` release. I'll fix it soon, then you can rebase this.

**Comment by pamungkaski** [comment]
@andrewgodwin okey

**Comment by andrewgodwin** [comment]
I've manually merged this in as part of the 1.2.0 release. Thanks for noticing it.

**Comment by pamungkaski** [comment]
@andrewgodwin No worries dude

**Pull request closed without merging**
