### PR TITLE
As mentioned in #199:

### PR DESCRIPTION
**Pull request by karolyi**
Since X-Forwarded-For is not to be trusted, and custom nginx
configurations can pass a X-Real-IP header, add two extra command
line parameters to be able to parse custom passed remote IP headers.

### CODE REVIEW

**Comment by karolyi** [comment]
referencing #199

**Comment by karolyi** [comment]
bump?

**Comment by andrewgodwin** [comment]
Sorry I didn't get to it before, but this isn't mergeable as it is right now - would need it to be before I review.

**Comment by karolyi** [comment]
bumpity bump?

**Comment by andrewgodwin** [comment]
Sorry, I don't get notifications unless there's a comment! Will merge this now - thanks!

**Comment by karolyi** [comment]
great stuff, thank you :)

now, the only remaining thing is an actual release, so I can use this in my project from the pypi source :)

**Comment by andrewgodwin** [comment]
Released in `2.2.3`!

**Pull request merged**
