### PR TITLE
Added runserver to Daphne. 

### PR DESCRIPTION
**Pull request by carltongibson**
Refs #428. 

- [x] Made daphne installable as a Django app.
- [x] Added system check to ensure daphne is installed before
       django.contrib.staticfiles.
- [x] Port runserver command.

### CODE REVIEW

**Comment by carltongibson** [comment]
Hey @kezabelle — no urgency, but wondering if you'd be interested by 79abfaeb2047cc7972017fe8165411d8e49a6f9d... 🤔 — it's a question of _what's the minimum to bootstrap the app registry here?_, preferably without going all the way to `pytest-django` etc. That seems to me your kind of ballpark. 😜

(Hope you're doing well!)

**Comment by carltongibson** [comment]
Hey @massover — I've moved the `runserver` command from Channels here. 

With a... 

```python
INSTALLED_APPS = [
    "daphne",
    ...
]
```

... it all seems to be working. 

I don't know if you've got a cycle to glance over for any gains? (No problem if not 🎁) 

I looked over your [standalone implementation](https://github.com/massover/asgi-runserver/blob/master/asgi_runserver/management/commands/runserver.py) but didn't want to add the `run_wsgi` like options here (at this stage). The final version, living in Django, eventually, one day, maybe 😜, will need to handle both protocols.

**Comment by carltongibson** [comment]
OK, I'm going to merge this as is, so that I can continue working. We can follow up with adjustments later if needed.

**Comment by gnat** [comment]
Tested, seems to work just fine with the psycopg3 PR as well! https://github.com/django/django/pull/15687

For those following along:
1. `python3 -m pip install git+https://github.com/django/daphne.git@7453ad9`
2. In `settings.py`
```python
INSTALLED_APPS = [
    "daphne",
    #...
]
#WSGI_APPLICATION = 'crdbtest.wsgi.application'
ASGI_APPLICATION = 'crdbtest.asgi.application'
```
3. `python3 ./manage.py runserver`

**Comment by carltongibson** [comment]
@gnat Thanks for testing! (More helpful than you think 🙂)

**Pull request merged**
